openapi: 3.0.0
info:
    title: Sample API
    description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
    version: 0.1.9
servers:
    - url: http://api.example.com/v1
      description: Optional server description, e.g. Main (production) server
    - url: http://staging-api.example.com
      description: Optional server description, e.g. Internal staging server for testing
paths:
    /users:
        post:
            summary: Creates a new user.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                id:
                                    type: string
                                    format: uuid
                                address:
                                    # default Content-Type for objects is `application/json`
                                    type: object
                                    properties: {}
                                profileImage:
                                    # default Content-Type for string/binary is `application/octet-stream`
                                    type: string
                                    format: binary
                                children:
                                    # default Content-Type for arrays is based on the `inner` type (text/plain here)
                                    type: array
                                    items:
                                        type: string
            responses:
                "201":
                    description: Created
